= Blockchain i IBM

== Wersja krótsza

Blockchain jest rozproszoną bazą danych, gdzie każda kolejna porcja informacji, zwana blokiem, jest nierozerwalnie związana z poprzednią, tworząc rzeczony łańcuch bloków. Bezpieczeństwo w blockchainie jest zapewnione dzięki zastosowanym mechanizmom kryptograficznym z pominięciem zaufanej trzeciej strony. W ten sposób możliwe stało się stworzenie kryptowalut takich jak Bitcoin, gdzie transakcje są wykonywane w rozproszonej sieci. Kluczowym elementem w systemie stworzonym przez anonimowego Satoshiego Nakamoto w 2008 r. jest dowód wykonania pracy (z ang. proof of work). Stanowi on w istocie metodę głosowania dostępnym sprzętem komputerowym. Jest on skuteczny, dopóki żadna pojedyncza grupa górników nie dysponuje większością mocy obliczeniowej. Innymi elementami wartymi wyróżnienia są chociażby transakcje podpisywane elektronicznie z wykorzystaniem kryptografii asymetrycznej, jak również drzewa Merkle, które stanowią efektywny model haszowania transakcji w bloku.

Poza rynkiem kryptowalut, blockchain można też odnaleźć w produktach koncernu IBM, który na przestrzeni lat stał się biegły we wdrożeniach tej technologii. Wraz z globalną marką samochodową Renault i pozostałymi partnerami stworzyli oni projekt XCEED, służący do śledzenia i certyfikacji wszelkich części samochodowych w ramach całego cyklu produkcyjnego i sprzedażowego. Zapewnienie takiego nadzoru okazuje się szczególnie ważne przy stale zmieniających się regulacjach.

Zainteresowanych zapraszam do przeczytania pełnej wersji artykułu na stronie: https://github.com/fyr-systems/articles/blob/main/pl/Blockchain_and_IBM.adoc.

== Wersja dłuższa

Blockchain jest rozproszoną bazą danych, gdzie każda kolejna porcja informacji, zwana blokiem, jest nierozerwalnie związana z poprzednią, tworząc rzeczony łańcuch bloków. Bezpieczeństwo w blockchainie jest zapewnione dzięki zastosowanym mechanizmom kryptograficznym z pominięciem zaufanej trzeciej strony. W ten sposób możliwe stało się stworzenie kryptowalut takich jak Bitcoin, gdzie transakcje są wykonywane w rozproszonej sieci. System stworzony przez anonimowego Satoshiego Nakamoto w 2008 r. składa się z kilku kluczowych elementów. Wszystkie wykonywane transakcje są podpisywane elektronicznie. Zgodnie z zasadami kryptografii asymetrycznej, wykonawca transakcji posługuje się swoim kluczem prywatnym, aby pozostali użytkownicy mogli zweryfikować jego tożsamość, używając jego klucza publicznego. W infrastrukturze Bitcoina kopie rejestru transakcji są przechowywane przez każdego uczestnika, więc konieczne było zaimplementowanie mechanizmu konsensusu, aby ustalać rzeczywisty stan rejestru w danym momencie. Dowód wykonania pracy (z ang. proof of work) stanowi w istocie metodę głosowania dostępnym sprzętem komputerowym. Jest on skuteczny, dopóki żadna pojedyncza grupa górników nie dysponuje większością mocy obliczeniowej w sieci blockchain Bitcoina. Wysiłek polega tutaj na znalezieniu specjalnej liczby zwanej "nonce", aby hasz nagłówka bloku zawierającego nonce był mniejszy od z góry określonego celu (z ang. target). Warto wspomnieć również o efektywnym modelu haszowania transakcji w bloku, tj. drzewie Merkle, które powstaje poprzez haszowanie transakcji parami aż do uzyskania pojedynczego hasza - korzenia drzewa Merkle.

Poza rynkiem kryptowalut, blockchain jest wykorzystywany m.in. do tworzenia zweryfikowanych zbiorów danych takich, jak np. w projekcie XCEED. Odpowiada za niego, biegły we wdrożeniach technologii blockchain, koncern IBM i globalna marka samochodowa Renault wraz z pozostałymi partnerami. Ta usługa służy do śledzenia i certyfikacji wszelkich części samochodowych w ramach całego cyklu produkcyjnego i sprzedażowego, co jest szczególnie ważne przy stale zmieniających się regulacjach.

Zainteresowanych zapraszam do przeczytania pełnej wersji artykułu na stronie: https://github.com/fyr-systems/articles/blob/main/pl/Blockchain_and_IBM.adoc.
